development:
  adapter: postgresql
  encoding: utf8
  database: assets_development
  pool: 5
  username: postgres
  password: icetea069

test: &test
  adapter: postgresql
  encoding: utf8
  database: assets_test
  pool: 5
  username: postgres
  password: icetea069

production:
  adapter: postgresql
  encoding: utf8
  database: assets_production
  pool: 5
  username: postgres
  password: icetea069

cucumber:
  <<: *test